# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='complaint.complaint')),
                ('action', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=20)),
                ('working', models.BooleanField()),
            ],
        ),
    ]
