# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_progress_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='complaint.complaint'),
        ),
    ]
