# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20170902_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
