# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_complaint_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='departments',
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.IntegerField(default=None),
        ),
    ]
