# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20170902_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
