# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_complaint_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed',
        ),
        migrations.AddField(
            model_name='progress',
            name='c_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='complaint.complaint'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
