# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_auto_20170902_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
