# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_auto_20170903_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default=None, upload_to='pictures/'),
        ),
    ]
