# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_auto_20170903_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='image',
        ),
    ]
